# Helix Theme: Sonokai IPS Balanced
# License: MIT
# Base palette from Sonokai, tuned for IPS panels:
# - Balanced saturation
# - Comfortable contrast
# - Cursorline that is clearly visible (cool tint) yet subtle

# -------------------------
# Syntax (language scopes)
# -------------------------
"type"                         = "blue"
"constant"                     = "fg"
"constant.numeric"             = "purple"
"constant.character.escape"    = "orange"
"string"                       = "yellow"
"comment"                      = "grey_dim"     # softened for long sessions on IPS
"variable"                     = "fg"
"variable.builtin"             = "purple"
"variable.parameter"           = "fg"
"variable.other.member"        = "orange"
"label"                        = "red"
"punctuation"                  = "grey"
"punctuation.special"          = "yellow"
"keyword"                      = "red"
"operator"                     = "red"
"function"                     = "green"
"function.builtin"             = "green"
"function.macro"               = "green"
"tag"                          = "yellow"
"namespace"                    = "blue"
"attribute"                    = "purple"
"constructor"                  = "blue"
"module"                       = "blue"
"special"                      = "orange"

# -------------------------
# Markup (Markdown etc.)
# -------------------------
"markup.heading.marker"        = "grey"
"markup.heading.1"             = { fg = "red",    modifiers = ["bold"] }
"markup.heading.2"             = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3"             = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4"             = { fg = "green",  modifiers = ["bold"] }
"markup.heading.5"             = { fg = "blue",   modifiers = ["bold"] }
"markup.heading.6"             = { fg = "fg",     modifiers = ["bold"] }
"markup.list"                  = "red"
"markup.bold"                  = { modifiers = ["bold"] }
"markup.italic"                = { modifiers = ["italic"] }
"markup.strikethrough"         = { modifiers = ["crossed_out"] }
"markup.link.url"              = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text"             = "purple"
"markup.quote"                 = "grey"
"markup.raw"                   = "green"

# -------------------------
# Diff
# -------------------------
"diff.plus"                    = "green"
"diff.delta"                   = "blue"
"diff.minus"                   = "red"

# -------------------------
# UI
# -------------------------
"ui.background"                = { bg = "bg0" }
"ui.background.separator"      = { fg = "bg3" }                  # pane borders
"ui.text"                      = "fg"
"ui.text.focus"                = "green"
"ui.text.inactive"             = "grey"

# Cursor & matches
"ui.cursor"                    = { modifiers = ["reversed"] }
"ui.cursor.insert"             = { fg = "black", bg = "grey" }
"ui.cursor.select"             = { fg = "bg0",   bg = "bg_purple_strong" }
"ui.cursor.match"              = { bg = "bg4" }                   # bracket/paren match

# Selection (purple, comfortable yet distinct)
"ui.selection"                 = { bg = "bg_purple" }             # regular selection (soft lilac)
"ui.selection.primary"         = { bg = "bg_purple_strong" }      # primary selection anchor (deeper purple)

# Line numbers & cursorline
"ui.linenr"                    = "grey"
"ui.linenr.selected"           = "fg"
"ui.cursorline.primary"        = { bg = "cursorline_bg" }         # cool-tinted lift

# Statusline
"ui.statusline"                = { fg = "fg",   bg = "bg3" }
"ui.statusline.inactive"       = { fg = "grey", bg = "bg1" }
"ui.statusline.normal"         = { fg = "bg0",  bg = "blue",   modifiers = ["bold"] }
"ui.statusline.insert"         = { fg = "bg0",  bg = "green",  modifiers = ["bold"] }
"ui.statusline.select"         = { fg = "bg0",  bg = "purple", modifiers = ["bold"] }

# Menus & popups
"ui.menu"                      = { fg = "fg",   bg = "bg2" }
"ui.menu.selected"             = { fg = "bg0",  bg = "bg_purple" }  # switched to purple for consistency
"ui.popup"                     = { fg = "grey", bg = "bg2" }
"ui.window"                    = { fg = "grey", bg = "bg0" }
"ui.help"                      = { fg = "fg",   bg = "bg1" }

# Virtual elements
"ui.virtual"                   = { fg = "bg4" }                   # whitespace markers, etc.
"ui.virtual.indent-guide"      = { fg = "bg4" }
"ui.virtual.ruler"             = { bg = "bg3" }
"ui.virtual.jump-label"        = { fg = "filled_red", modifiers = ["bold"] }

# Highlights (distinct from selection)
"ui.highlight"                 = { bg = "diff_yellow" }

# Messages
info                           = { fg = "green",  bg = "bg2" }
hint                           = { fg = "blue",   bg = "bg2", modifiers = ["bold"] }
warning                        = { fg = "yellow", bg = "bg2", modifiers = ["bold"] }
error                          = { fg = "red",    bg = "bg2", modifiers = ["bold"] }

# Diagnostics
"diagnostic.info"              = { underline = { style = "curl", color = "green" } }
"diagnostic.hint"              = { underline = { style = "curl", color = "blue" } }
"diagnostic.warning"           = { underline = { style = "curl", color = "yellow" } }
"diagnostic.error"             = { underline = { style = "curl", color = "red" } }
"diagnostic.unnecessary"       = { modifiers = ["dim"] }
"diagnostic.deprecated"        = { modifiers = ["crossed_out"] }

# -------------------------
# Palette (must be last)
# -------------------------
[palette]
black          = "#181A1C"
bg_dim         = "#24272E"
bg0            = "#2A2F38"  # main background (comfortable dark slate)
bg1            = "#33353f"  # low-contrast surfaces
bg2            = "#363944"  # popup/menu
bg3            = "#3b3e48"  # statusline inactive / ruler / separators
bg4            = "#414550"  # guides & match highlights
bg5            = "#444852"  # alt selection
bg_red         = "#ff6077"
diff_red       = "#55393d"
bg_green       = "#a7df78"
diff_green     = "#394634"
bg_blue        = "#85d3f2"
diff_blue      = "#354157"
diff_yellow    = "#4e432f"  # warm highlight area

# Purple selection tones tuned for IPS:
bg_purple         = "#b7a8f6"  # soft lilac (regular selection)
bg_purple_strong  = "#8b78da"  # deeper purple (primary selection / selection cursor)

# Cursorline: slightly cooler and ~8–10% lighter than bg0 for IPS clarity
cursorline_bg   = "#343A44"

fg              = "#e2e2e3"
red             = "#fc5d7c"
orange          = "#f39660"
yellow          = "#e7c664"
green           = "#9ed072"
cyan            = "#8dd0b6"
blue            = "#76cce0"
purple          = "#b39df3"
grey            = "#7f8490"
grey_dim        = "#595f6f"
filled_red      = "#ff6188"
