# Helix Theme: Sonokai Contrast (fixed)
# License: MIT
# Base: https://github.com/sainnhe/sonokai

# -------------------------
# Syntax (language scopes)
# -------------------------
"type"                         = "blue"
"constant"                     = "fg"
"constant.numeric"             = "purple"
"constant.character.escape"    = "orange"
"string"                       = "yellow"
"comment"                      = "grey_dim"     # slightly dim for comfort
"variable"                     = "fg"
"variable.builtin"             = "purple"
"variable.parameter"           = "fg"
"variable.other.member"        = "orange"
"label"                        = "red"
"punctuation"                  = "grey"
"punctuation.special"          = "yellow"
"keyword"                      = "red"
"operator"                     = "red"
"function"                     = "green"
"function.builtin"             = "green"
"function.macro"               = "green"
"tag"                          = "yellow"
"namespace"                    = "blue"
"attribute"                    = "purple"
"constructor"                  = "blue"
"module"                       = "blue"
"special"                      = "orange"

# -------------------------
# Markup (Markdown etc.)
# -------------------------
"markup.heading.marker"        = "grey"
"markup.heading.1"             = { fg = "red",    modifiers = ["bold"] }
"markup.heading.2"             = { fg = "orange", modifiers = ["bold"] }
"markup.heading.3"             = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4"             = { fg = "green",  modifiers = ["bold"] }
"markup.heading.5"             = { fg = "blue",   modifiers = ["bold"] }
"markup.heading.6"             = { fg = "fg",     modifiers = ["bold"] }
"markup.list"                  = "red"
"markup.bold"                  = { modifiers = ["bold"] }
"markup.italic"                = { modifiers = ["italic"] }
"markup.strikethrough"         = { modifiers = ["crossed_out"] }
"markup.link.url"              = { fg = "blue", modifiers = ["underlined"] }
"markup.link.text"             = "purple"
"markup.quote"                 = "grey"
"markup.raw"                   = "green"

# -------------------------
# Diff
# -------------------------
"diff.plus"                    = "green"
"diff.delta"                   = "blue"
"diff.minus"                   = "red"

# -------------------------
# UI
# -------------------------
"ui.background"                = { bg = "bg0" }
"ui.text"                      = "fg"
"ui.text.focus"                = "green"

# Cursor & lines
"ui.cursor"                    = { modifiers = ["reversed"] }
"ui.cursor.insert"             = { fg = "black", bg = "grey" }
"ui.cursor.select"             = { fg = "bg0", bg = "bg_blue" }
"ui.cursor.match"              = { bg = "bg4" }

# Selection (required by Helix)
"ui.selection"                 = { bg = "bg_blue" }
"ui.selection.primary"         = { bg = "bg_green" }

# Line numbers & cursorline
"ui.linenr"                    = "grey"
"ui.linenr.selected"           = "fg"
"ui.cursorline.primary"        = { bg = "bg1" }

# Statusline
"ui.statusline"                = { fg = "fg", bg = "bg3" }
"ui.statusline.inactive"       = { fg = "grey", bg = "bg1" }
"ui.statusline.normal"         = { fg = "bg0", bg = "blue",   modifiers = ["bold"] }
"ui.statusline.insert"         = { fg = "bg0", bg = "green",  modifiers = ["bold"] }
"ui.statusline.select"         = { fg = "bg0", bg = "purple", modifiers = ["bold"] }

# Menus & windows
"ui.menu"                      = { fg = "fg", bg = "bg2" }
"ui.menu.selected"             = { fg = "bg0", bg = "green" }
"ui.popup"                     = { fg = "grey", bg = "bg2" }
"ui.window"                    = { fg = "grey", bg = "bg0" }
"ui.help"                      = { fg = "fg",  bg = "bg1" }

# Virtual elements
"ui.virtual"                   = { fg = "bg4" }                # guides/whitespace indicators
"ui.virtual.ruler"             = { bg = "bg3" }
"ui.virtual.jump-label"        = { fg = "filled_red", modifiers = ["bold"] }

# Highlights
"ui.highlight"                 = { bg = "diff_yellow" }        # warm highlight distinct from selection

# Messages
info                           = { fg = "green",  bg = "bg2" }
hint                           = { fg = "blue",   bg = "bg2", modifiers = ["bold"] }
warning                        = { fg = "yellow", bg = "bg2", modifiers = ["bold"] }
error                          = { fg = "red",    bg = "bg2", modifiers = ["bold"] }

# Diagnostics
"diagnostic.info"              = { underline = { style = "curl", color = "green" } }
"diagnostic.hint"              = { underline = { style = "curl", color = "blue" } }
"diagnostic.warning"           = { underline = { style = "curl", color = "yellow" } }
"diagnostic.error"             = { underline = { style = "curl", color = "red" } }
"diagnostic.unnecessary"       = { modifiers = ["dim"] }
"diagnostic.deprecated"        = { modifiers = ["crossed_out"] }

# -------------------------
# Palette (must be last)
# -------------------------
[palette]
black      = "#181A1C"
bg_dim     = "#24272E"
bg0        = "#2A2F38"  # main background
bg1        = "#33353f"  # cursorline
bg2        = "#363944"  # popup/menu
bg3        = "#3b3e48"  # statusline inactive
bg4        = "#414550"  # guides/match
bg5        = "#444852"  # alt selection
bg_red     = "#ff6077"
diff_red   = "#55393d"
bg_green   = "#a7df78"
diff_green = "#394634"
bg_blue    = "#85d3f2"
diff_blue  = "#354157"
diff_yellow= "#4e432f"  # warm highlight area
fg         = "#e2e2e3"
red        = "#fc5d7c"
orange     = "#f39660"
yellow     = "#e7c664"
green      = "#9ed072"
cyan       = "#8dd0b6"
blue       = "#76cce0"
purple     = "#b39df3"
grey       = "#7f8490"
grey_dim   = "#595f6f"
filled_red = "#ff6188"
