name: cloudreve
services:
  cloudreve:
    image: cloudreve/cloudreve:latest
    container_name: cloudreve_app
    depends_on:
      - postgresql
      - redis
    restart: unless-stopped
    expose:
      - 5212
    environment:
      - CR_CONF_Database.Type=postgres
      - CR_CONF_Database.Host=postgresql
      - CR_CONF_Database.User=cloudreve
      - CR_CONF_Database.Name=cloudreve
      - CR_CONF_Database.Port=5432
      - CR_CONF_Redis.Server=redis:6379
    volumes:
      - cloudreve_app_data:/cloudreve/data
    networks:
      - web_network
      - cloudreve_internal

  postgresql:
    image: postgres:17
    container_name: cloudreve_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=cloudreve
      - POSTGRES_DB=cloudreve
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - cloudreve_db_data:/var/lib/postgresql/data
    networks:
      - cloudreve_internal

  redis:
    image: redis:latest
    container_name: cloudreve_redis
    restart: unless-stopped
    volumes:
      - cloudreve_redis_data:/data
    networks:
      - cloudreve_internal

volumes:
  cloudreve_app_data:
  cloudreve_db_data:
  cloudreve_redis_data:

networks:
  web_network:
    external: true

  cloudreve_internal:
    driver: bridge
