version: "3.8"
name: nextcloud
services:
  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super_secure_root_password # Change this
      - MYSQL_PASSWORD=secure_database_password # Change this
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: unless-stopped

  app:
    # on nginx proxy manager nexcloud_app:80
    image: nextcloud:33-apache
    container_name: nextcloud_app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    networks:
      - default
      - web_network
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=secure_database_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

      - NEXTCLOUD_TRUSTED_DOMAINS=drive.domain.com
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=drive.domain.com
      - OVERWRITECLIURL=https://drive.domain.com
      # add your reverse proxy IP/CIDR here if needed
      # - TRUSTED_PROXIES=172.20.0.0/16
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379

      - PHP_MEMORY_LIMIT=4G
      - PHP_UPLOAD_LIMIT=50G

    cron:
      # use the SAME tag as app
      image: nextcloud:33-apache
      container_name: nextcloud_cron
      restart: unless-stopped
      entrypoint: /cron.sh
      depends_on:
        - db
        - redis
      volumes:
        - nextcloud_data:/var/www/html

volumes:
  nextcloud_db:
  nextcloud_data:

networks:
  web_network:
    external: true

# Note
# if you use Nginx Proxy Manager to manage service please add this on npm advance tab
# it will match with configuration docker above

# client_max_body_size 50G;
# client_body_timeout 3600s;
# proxy_read_timeout 3600s;
# proxy_send_timeout 3600s;
# send_timeout 3600s;

# location = /.well-known/carddav {
#     return 301 https://$host/remote.php/dav;
# }
# location = /.well-known/caldav {
#     return 301 https://$host/remote.php/dav;
# }

