version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super_secure_root_password # Change this
      - MYSQL_PASSWORD=secure_database_password # Change this
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    # on nginx proxy manager nexcloud_app:80
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - default
      - web_network
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=secure_database_password # Must match the db password above
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=drive.domain.com
      - OVERWRITEPROTOCOL=https
      - PHP_MEMORY_LIMIT=4G # Crucial for large video workflows
      - PHP_UPLOAD_LIMIT=50G # Set this to handle your largest raw files
      - UPLOAD_MAX_FILESIZE=50G
      - POST_MAX_SIZE=50G

volumes:
  nextcloud_db:
  nextcloud_data:

networks:
  web_network:
    external: true
