name: wikijs

services:
  wikijs-db:
    image: postgres:15-alpine
    container_name: wikijs-db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: none
    restart: unless-stopped
    volumes:
      - wiki-data:/var/lib/postgresql/data
    networks:
      - internal

  wikijs-app:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs-app
    depends_on:
      - wikijs-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - internal
      - web_network

volumes:
  wiki-data:

networks:
  internal:
    driver: bridge

  web_network:
    external: true
