name: wikijs

services:
  db:
    image: postgres:15-alpine
    container_name: wikijs_db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: none
    restart: unless-stopped
    volumes:
      - wikijs_db_data:/var/lib/postgresql/data
    networks:
      - internal

  app:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs_app
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - internal
      - web_network

volumes:
  wikijs_db_data:

networks:
  internal:
    driver: bridge

  web_network:
    external: true
