-- Plugin imports are intentionally ordered. Some configurations depend on
-- plugins initialized above them, so changing this order can break startup or
-- plugin behavior. Add new plugin imports in the correct dependency order.
require("plugins.catppuccin")
require("plugins.lazydev")
require("plugins.snacks")
require("plugins.mini")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.completion")
require("plugins.conform")
require("plugins.gitsign")
require("plugins.fzf")
require("plugins.which-key")
require("plugins.overseer")
require("plugins.gitsign")
require("plugins.codediff")
require("plugins.grug-far")
require("plugins.multicursor")
require("plugins.todo-comments")
require("plugins.trouble")
